---
version: 2
updates:

  # GitHub Workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "12 01 * * SAT"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels: ["deps"]

  # npm
  - package-ecosystem: "npm"
    directory: "/js"
    schedule:
      interval: "cron"
      cronjob: "38 01 * * SAT"
    commit-message:
      prefix: "update"
      include: scope
    ignore:
      - dependency-name: "eslint"
        update-types:
          - "version-update:semver-major"
    labels: ["deps"]
    groups:
      all:
        patterns: ["*"]
