name: biome-check

env:
  documentation: 'https://github.com/indexdata/reservoir-scripts/blob/main/js/README.md#verify-matchers-development'

on:
  workflow_dispatch:
  push:
    paths:
      - '**.mjs'
      - '**.js'
      - '**.json'
  pull_request:
    paths:
      - '**.mjs'
      - '**.js'
      - '**.json'

permissions:
  contents: read

jobs:
  biome-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./js
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Show documentation
        run: |
          echo "Documentation: ${{ env.documentation }}" | tee -a "$GITHUB_STEP_SUMMARY"

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          working-dir: 'js'

      - name: Show biome version
        run: biome version

      - name: Run Biome
        run: biome ci --error-on-warnings .
