name: prettier-check

env:
  NODEJS_VERSION: '22'

on:
  workflow_dispatch:
  push:
    paths:
      - '**.mjs'
      - '**.js'
      - '**.json'
      - '.prettierrc'
  pull_request:
    paths:
      - '**.mjs'
      - '**.js'
      - '**.json'
      - '.prettierrc'
jobs:
  prettier-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./js
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Do setup-node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODEJS_VERSION }}
          check-latest: true
      - name: Do npm install
        run: npm install
      - name: Do prettier-check
        run: npm run prettier-check
