name: schedule-deployment

env:
  documentation: 'https://github.com/indexdata/reservoir-scripts/blob/main/js/README.md#workflow-schedule-deployment'

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Deployment action'
        required: true
        default: 'add'
        type: choice
        options:
          - 'add'
          - 'remove'
      deployments:
        description: 'List of matchers, e.g. goldrush2024,isxn'
        required: true
        type: string

jobs:
  schedule-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Show documentation
        run: |
          echo "Documentation: ${{ env.documentation }}" | tee -a "$GITHUB_STEP_SUMMARY"

      - name: Fail if attempt dispatch on default branch
        if: github.ref_name == github.event.repository.default_branch
        run: |
          echo "The workflow_dispatch is only available for non-default branches." | tee -a "$GITHUB_STEP_SUMMARY"
          exit 1

      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Verify inputs
        id: verify-inputs
        env:
          DEPLOYMENTS: ${{ inputs.deployments }}
        shell: bash
        run: |
          IFS=', ' read -r -a deployments <<< "${DEPLOYMENTS//[[:blank:]]/}"
          # declare -p deployments
          declare -a errors
          declare -a schedules
          for matcher in "${deployments[@]}"; do
            echo "matcher=${matcher}"
            if ! [ -d "js/matchers/${matcher}" ]; then
              errors+=("The matcher '${matcher}' is not found.")
              continue
            fi
            sha_short=$(git rev-parse HEAD | cut -c 1-7)
            schedules+=("${matcher}:${sha_short}")
          done
          if [ ${#errors[@]} -gt 0 ]; then
            printf "ERROR: %s\n" "${errors[@]}"
            exit 1
          else
            schedule=$(printf "%s," "${schedules[@]}" | sed s/,$//)
            echo "schedule=$schedule" | tee -a "$GITHUB_OUTPUT"
          fi

      - name: Show schedule summary
        run: |
          echo "schedule: ${{ inputs.action }}: ${{ steps.verify-inputs.outputs.schedule }}" >> "$GITHUB_STEP_SUMMARY"

      - name: Append JSONL to file
        env:
          ACTION: ${{ inputs.action }}
          SCHEDULE: ${{ steps.verify-inputs.outputs.schedule }}
          JOB_ID: ${{ github.run_number }}
        run: python3 .github/workflows/scripts/schedule_deployments.py -l info

      - name: Show recent schedule
        run: tail -5 js/schedule-deployments.jsonl

      - name: Do git pull
        run: git pull

      - name: Commit git changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Apply schedule deployments
          file_pattern: js/schedule-deployments.jsonl
