name: schedule-deployment

env:
  documentation: 'https://github.com/indexdata/matchkeys/blob/main/js/README.md#schedule-deployment'

on:
  workflow_dispatch:
    inputs:
      deployments:
        description: 'List of matchkeys with short commit hash SHA e.g. goldrush2024:1163910,isxn:d88522c'
        required: true
        type: string
jobs:
  schedule-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Show documentation
        run: |
          echo "Documentation: ${{ env.documentation }}" | tee -a "$GITHUB_STEP_SUMMARY"

      - name: Verify input
        env:
          DEPLOYMENTS: ${{ inputs.deployments }}
        shell: bash
        run: |
          IFS=', ' read -r -a deployments <<< "${DEPLOYMENTS//[[:blank:]]/}"
          # declare -p deployments
          declare -a errors
          for deployment in "${deployments[@]}"; do
            echo "deployment=${deployment}"
            if [[ ! "${deployment}" =~ : ]]; then
              errors+=("Missing colon delimiter in deployment '${deployment}'.")
              continue
            fi
            matchkey=$(echo "${deployment}" | cut -d ':' -f 1)
            echo "matchkey=${matchkey}"
            if ! [ -d "js/matchkeys/${matchkey}" ]; then
              errors+=("The matchkey '${matchkey}' is not found.")
            fi
            sha=$(echo "${deployment}" | cut -d ':' -f 2)
            echo "sha=${sha}"
            if [ -z "${sha}" ]; then
              errors+=("The SHA is missing for matchkey '${matchkey}'.")
              continue
            fi
            branch=$(git name-rev --name-only "${sha}" 2>&1 | sed 's/~.*$//')
            if [[ "${branch}" =~ .*"Could not get".* ]]; then
              errors+=("Could not find SHA '${sha}' for matchkey '${matchkey}'.")
              continue
            fi
            echo "branch=${branch}"
          done
          if [ ${#errors[@]} -gt 0 ]; then
            printf "ERROR: %s\n" "${errors[@]}"
            exit 1
          fi
